Repository NCI-GDC/gdc-frontend-framework, pull requests merged in 2023-12, with the labels that each got.

#828 PEAR-1642 - Cohort Comparison - Clicking on "Open Venn Diagram" causes unexpected error and user is stuck in loop
  packages/portal-proto/src/components/ClearStoreErrorBoundary.tsx
  packages/portal-proto/src/features/set-operations/CountButtonWrapperForSetsAndCases.tsx
Labels: 2.11.0

#691 PEAR 1322 / 1621 - Mutations button, survival plot in Mutations tab not plotting for a mutation
  packages/core/src/features/genomic/ssmsTableSlice.ts
  packages/portal-proto/src/features/GenomicTables/GenesTable/utils.tsx
  packages/portal-proto/src/features/GenomicTables/SomaticMutationsTable/SMTableContainer.tsx
  packages/portal-proto/src/features/genomic/GenesAndMutationFrequencyAnalysisTool.tsx
Labels: 2.11.0

#840 PEAR-1566: Don't allow cohorts to have the same name as the unsaved_cohort
  packages/portal-proto/__mocks__/sharedMockData.ts
  packages/portal-proto/src/components/ErrorMessage.tsx
  packages/portal-proto/src/components/Modals/CreateCohortModal.tsx
  packages/portal-proto/src/components/Modals/SaveCohortModal.tsx
  packages/portal-proto/src/components/Modals/SaveOrCreateEntityModal.tsx
  packages/portal-proto/src/components/Modals/tests/SaveOrCreateEntityModal.unit.test.tsx
  packages/portal-proto/src/components/SaveSetButton.tsx
Labels: milestone

#820 PEAR-1564 - Cohort Save-As feature
  packages/core/src/features/cohort/availableCohortsSlice.ts
  packages/portal-proto/src/components/DropdownWithIcon/DropdownWithIcon.tsx
  packages/portal-proto/src/components/Modals/SaveCohortModal.tsx
  packages/portal-proto/src/components/Modals/SaveCohortModal.unit.test.tsx
  packages/portal-proto/src/features/cohortBuilder/CohortManager.tsx
  packages/portal-proto/src/features/proteinpaint/OncoMatrixWrapper.unit.test.tsx
  packages/portal-proto/src/features/proteinpaint/ProteinPaintWrapper.unit.test.tsx
Labels: milestone

#854 PEAR-1541+1551: Add a send feedback modal and new nav button for video guides
  package-lock.json
  packages/portal-proto/package.json
  packages/portal-proto/src/components/Modals/SendFeedbackModal.tsx
  packages/portal-proto/src/features/layout/Header.tsx
Labels: milestone

#836 PEAR-1633: Modals - 508 compliance issues
  packages/portal-proto/src/components/Modals/SummaryModal/SummaryModal.tsx
  packages/portal-proto/src/components/Summary/SummaryCard.tsx
  packages/portal-proto/src/features/cases/CasesView/utils.tsx
Labels: 508

#843 PEAR-1644: use mantine component for quicksearch
  packages/portal-proto/src/components/List/TraversableList.tsx
  packages/portal-proto/src/components/List/tests/TraversableList.unit.test.tsx
  packages/portal-proto/src/components/QuickSearch/QuickSearch.tsx
Labels: 508

#874 PEAR-1686: fix Cohort bar scroll and lables in summary view
  packages/portal-proto/src/features/charts/EnumFacetChart.tsx
  packages/portal-proto/src/features/cohortBuilder/ContextBar.tsx
Labels: 508

#884 PEAR-1704 - Notification close button fails 508 compliance
  packages/portal-proto/src/components/Modals/SetModals/AddToSetModal.tsx
  packages/portal-proto/src/components/Modals/SetModals/RemoveFromSetModal.tsx
  packages/portal-proto/src/components/Modals/SetModals/SaveSelectionModal.tsx
  packages/portal-proto/src/components/Modals/SetModals/UpdateFiltersButton.tsx
  packages/portal-proto/src/components/SaveSetButton.tsx
  packages/portal-proto/src/features/cart/updateCart.tsx
  packages/portal-proto/src/features/layout/Header.tsx
  packages/portal-proto/src/features/layout/UserFlowVariedPages.tsx
  packages/portal-proto/src/utils/download.tsx
Labels: 508

#878 PEAR-1697: add aria-hidden attribute for when column ordering button is invisible/visible
  packages/portal-proto/src/components/Table/ColumnOrdering.tsx
Labels: 508

#883 PEAR-1694: convert some buttons into links, cleanup some labels and alt tags
  packages/portal-proto/src/features/layout/Header.tsx
  packages/portal-proto/src/features/user-flow/workflow/AnalysisCard.tsx
  packages/portal-proto/src/features/user-flow/workflow/AnalysisWorkspace.tsx
  packages/portal-proto/src/features/user-flow/workflow/CoreToolCard.tsx
  packages/portal-proto/src/features/user-flow/workflow/navigation-utils.tsx
  packages/portal-proto/src/features/user-flow/workflow/registeredApps.tsx
Labels: 508
