Repository NCI-GDC/gdc-frontend-framework, pull requests merged in 2024-01, with the labels that each got.

#891 Restored and added data-testids QA-2122
  packages/portal-proto/src/features/layout/Header.tsx
  packages/portal-proto/src/features/user-flow/workflow/AnalysisWorkspace.tsx
Labels: 2.12.0

#892 Qa 2122 test automation update 2.12.0 round 2
  holmes-py/specs/gdc_data_portal_v2/analysis_center/navigation.spec
  holmes-py/specs/gdc_data_portal_v2/repository/add_a_file_filter.spec
  holmes-py/step_impl/apps/gdc_data_portal_v2/pages/analysis_center_page.py
  holmes-py/step_impl/apps/gdc_data_portal_v2/pages/header_section.py
  holmes-py/step_impl/apps/gdc_data_portal_v2/pages/repository_page.py
  holmes-py/step_impl/apps/gdc_data_portal_v2/step_defs/analysis_center_page_steps.py
  holmes-py/step_impl/apps/gdc_data_portal_v2/step_defs/generic_steps.py
  holmes-py/step_impl/base/base_page.py
Labels: 2.12.0

#881 PEAR-1699 - 508 compliance, data table headers are appropriately identified
  packages/portal-proto/src/components/HorizontalTable.tsx
  packages/portal-proto/src/components/InputEntityList/MatchedTable.tsx
  packages/portal-proto/src/components/Table/VerticalTable.tsx
  packages/portal-proto/src/components/Table/types.ts
Labels: 508

#882 PEAR-1698 - 508 compliance, related form elements are grouped with fieldset/legend.
  packages/portal-proto/src/features/cDave/ContinuousBinningModal/ContinuousBinningModal.tsx
  packages/portal-proto/src/features/facets/DateRangeFacet.tsx
  packages/portal-proto/src/features/facets/EnumFacet.tsx
  packages/portal-proto/src/features/facets/NumericRangeFacet.tsx
Labels: 508

#886 PEAR-1693 - 508 compliance, all image buttons have appropriate, concise alt text
  packages/portal-proto/src/components/CohortCreationButton.tsx
  packages/portal-proto/src/components/SwitchSpring/shared/SwitchSpring.tsx
  packages/portal-proto/src/components/Table/VerticalTable.tsx
  packages/portal-proto/src/features/biospecimen/utils.tsx
  packages/portal-proto/src/features/facets/EnumFacet.tsx
  packages/portal-proto/src/features/user-flow/workflow/AnalysisCard.tsx
Labels: 508

#894 PEAR-1694: Customize Columns Menu dropdown refactor
  packages/portal-proto/src/components/Table/ColumnOrdering.tsx
Labels: 508

#897 add "relative" to root divs for OncoMatrix and GeneExpression wrappers
  packages/portal-proto/src/features/proteinpaint/GeneExpressionWrapper.tsx
  packages/portal-proto/src/features/proteinpaint/OncoMatrixWrapper.tsx
Labels: jacob

#802 PEAR-1544: Table checkbox accessibility
  packages/portal-proto/src/components/Modals/SetModals/SavedSets.tsx
  packages/portal-proto/src/components/Modals/SetModals/SetTable.tsx
  packages/portal-proto/src/components/PopupIconButton/PopupIconButton.tsx
  packages/portal-proto/src/features/GenomicTables/GenesTable/GTableContainer.tsx
  packages/portal-proto/src/features/GenomicTables/GenesTable/utils.tsx
  packages/portal-proto/src/features/GenomicTables/SomaticMutationsTable/SMTableContainer.tsx
  packages/portal-proto/src/features/GenomicTables/SomaticMutationsTable/TableComponents/SMTableProteinChange.tsx
  packages/portal-proto/src/features/GenomicTables/SomaticMutationsTable/utils.tsx
  packages/portal-proto/src/features/cases/CasesView/CasesView.tsx
  packages/portal-proto/src/features/cases/CasesView/utils.tsx
  packages/portal-proto/src/features/facets/EnumFacet.tsx
  packages/portal-proto/src/features/manageSets/ManageSetsTable.tsx
  packages/portal-proto/src/features/projectsCenter/ProjectsTable.tsx
  packages/portal-proto/src/features/set-operations/SelectionPanel.tsx
  packages/portal-proto/src/features/set-operations/SetOperationTable.tsx
Labels: 508

#889 PEAR-1685: Add default {focused : true} default prop to Tooltip
  packages/portal-proto/src/pages/_app.tsx
Labels: 508

#893 PEAR-1672: Change styles to make header, context bar, cohort bar responsive
  packages/portal-proto/src/components/CollapsibleContainer.tsx
  packages/portal-proto/src/features/cohortBuilder/ContextBar.tsx
  packages/portal-proto/src/features/layout/Header.tsx
Labels: 508

#917 PEAR-1731: fix spinning case counts in save -> change cohort -> saveAs
  packages/core/src/features/cohort/availableCohortsSlice.ts
  packages/core/src/listeners.ts
Labels: jacob

#925 PEAR-1746: Fix for Mutation Frequency genes graph having incorrect denominator
  packages/core/src/features/genomic/genesFrequencyChartSlice.ts
Labels: 2.12.0, jacob

#927 PEAR-1744 - Sequence Reads and BAM Slicing case counts incorrect
  packages/core/src/features/cohort/cohortCountsQuery.ts
Labels: jacob

#928 PEAR-1731,1743: Fix Case Counts race condition and infinite spinning
  packages/core/src/features/cohort/availableCohortsSlice.ts
  packages/core/src/features/cohort/cohortCountsQuery.ts
  packages/core/src/listeners.ts
  packages/portal-proto/src/components/Modals/SaveCohortModal.tsx
  packages/portal-proto/src/features/cohortBuilder/CohortManager.tsx
Labels: jacob

#932 PEAR-1751: resolve race condition for facets
  packages/core/src/features/facets/continuousAggregationApi.ts
  packages/core/src/features/facets/continuousAggregationApi.unit.test.ts
  packages/core/src/features/facets/continuousAggregationSlice.ts
  packages/core/src/features/facets/facetApiGQL.ts
  packages/core/src/features/facets/facetSliceGQL.ts
  packages/core/src/features/facets/types.ts
  packages/portal-proto/src/features/repositoryApp/repositoryFacetSlice.ts
  packages/portal-proto/src/features/repositoryApp/repositoryRangeFacet.ts
Labels: jacob

#930 PEAR-1711 - Case counts on Gene Expression card
  packages/core/src/features/cohort/availableCohortsSlice.ts
  packages/core/src/features/cohort/cohortCountsQuery.ts
  packages/core/src/features/cohort/tests/mockData.ts
  packages/portal-proto/src/features/user-flow/workflow/registeredApps.tsx
Labels: jacob

#933 PEAR-1752: add requestID to most slices that need it.
  packages/core/src/features/annotations/annotationsSlice.ts
  packages/core/src/features/biospecimen/biospecimenSlice.ts
  packages/core/src/features/cancerDistribution/cnvPlot.ts
  packages/core/src/features/cancerDistribution/ssmPlot.ts
  packages/core/src/features/cart/cartSummarySlice.ts
  packages/core/src/features/cases/caseSummarySlice.ts
  packages/core/src/features/clinicalDataAnalysis/clinicalFieldsSlice.ts
  packages/core/src/features/cohortComparison/vennDiagramSlice.ts
  packages/core/src/features/files/totalFileSizeSlice.ts
  packages/core/src/features/genomic/geneSummary/geneSummarySlice.ts
  packages/core/src/features/genomic/genesFrequencyChartSlice.ts
  packages/core/src/features/genomic/genesTableSlice.ts
  packages/core/src/features/genomic/ssmsConsequenceTableSlice.ts
  packages/core/src/features/genomic/ssmsSummary/ssmsSummarySlice.ts
  packages/core/src/features/genomic/topGenesSSMSSlice.ts
  packages/core/src/features/history/historySlice.ts
  packages/core/src/features/imageDetails/imageDetailsSlice.ts
  packages/core/src/features/imageDetails/types.ts
  packages/core/src/features/quickSearch/quickSearch.ts
  packages/core/src/features/summary/totalCountsSlice.ts
  packages/core/src/features/summary/totalCountsSlice.unit.test.ts
  packages/portal-proto/src/features/repositoryApp/slideCountSlice.ts
Labels: jacob

#931 PEAR-1749: Add a custom 404 page
  packages/portal-proto/src/features/layout/Footer.tsx
  packages/portal-proto/src/pages/404.tsx
Labels: jacob

#935 PEAR-1766: case count fix for copyToSavedCohort
  packages/core/src/features/cohort/availableCohortsSlice.ts
  packages/core/src/features/cohort/cohortCountsQuery.ts
  packages/portal-proto/src/components/Modals/SaveCohortModal.tsx
Labels: jacob

#936 PEAR-1762: Clean up image viewer/detail slice
  packages/core/src/features/imageDetails/imageDetailsSlice.ts
  packages/core/src/features/imageDetails/imageViewer.ts
  packages/portal-proto/src/components/ImageViewer/MultipleImageViewer.tsx
Labels: jacob

#915 Refactor/line item68 3
  holmes-py/step_impl/base/base_page.py
  packages/portal-proto/src/components/CohortCreationButton.tsx
  packages/portal-proto/src/components/InputEntityList/InputEntityList.unit.test.tsx
  packages/portal-proto/src/components/Modals/SaveCohortModal.unit.test.tsx
  packages/portal-proto/src/components/Modals/SaveOrCreateEntityModal.tsx
  packages/portal-proto/src/components/Table/ExpandRowComponent.tsx
  packages/portal-proto/src/components/Table/VerticalTable.tsx
  packages/portal-proto/src/features/biospecimen/Biospecimen.tsx
  packages/portal-proto/src/features/cases/ClinicalSummary/ClinicalSummary.tsx
  packages/portal-proto/src/features/files/FileVersions.tsx
  packages/portal-proto/src/features/projects/ProjectView.tsx
  packages/portal-proto/src/pages/_app.tsx
Labels: 508

#941 update the proteinpaint-client version to 2.39.6
  package-lock.json
  packages/portal-proto/package.json
  packages/portal-proto/src/features/proteinpaint/GeneExpressionWrapper.tsx
  packages/portal-proto/src/features/proteinpaint/OncoMatrixWrapper.tsx
Labels: jacob

#943 PEAR-1572 - Cancer gene census toggle not always reflecting user's change
  packages/portal-proto/src/features/facets/ToggleFacet.tsx
Labels: jacob

#954 PEAR-1793 - Endless(?) graphql calls, cannot switch to another cohort successfully
  packages/portal-proto/src/features/cohortBuilder/ContextBar.tsx
Labels: jacob

#952 PEAR-1789 - Remove unused pages
  packages/portal-proto/public/nci-color-standards.jpg
  packages/portal-proto/src/pages/api/counter.ts
  packages/portal-proto/src/pages/app/[appId].tsx
  packages/portal-proto/src/pages/colors.tsx
  packages/portal-proto/src/pages/styleguide.tsx
Labels: jacob
